version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/ypm
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_user"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A ypm worker -l info -P prefork
    volumes:
      - .:/ypm
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A ypm beat -l info
    volumes:
      - .:/ypm
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
